/**
 * Task Action Types
 *
 * Discriminated union of all possible actions that can be dispatched
 * to the task reducer. TypeScript will narrow the payload type based
 * on the action.type property.
 *
 * @see data-model.md for state transition details
 * @see taskReducer.ts for action handler implementation
 */

import type { Task, FilterState, SortState, RecurrencePattern } from '../lib/types/task';

/**
 * Action to create a new task
 *
 * Payload excludes id, createdAt, updatedAt (generated by reducer)
 */
export type AddTaskAction = {
  type: 'ADD_TASK';
  payload: {
    title: string;
    description?: string;
    priority: 'low' | 'medium' | 'high';
    dueDate?: string; // ISO 8601 date string (YYYY-MM-DD)
    tags?: string[];
    recurrence?: RecurrencePattern;
  };
};

/**
 * Action to update an existing task
 *
 * Payload includes task id and partial updates
 * updatedAt timestamp is set automatically by reducer
 */
export type UpdateTaskAction = {
  type: 'UPDATE_TASK';
  payload: {
    id: string;
    updates: Partial<{
      title: string;
      description?: string;
      priority: 'low' | 'medium' | 'high';
      dueDate?: string;
      tags?: string[];
      recurrence?: RecurrencePattern;
    }>;
  };
};

/**
 * Action to toggle task completion status
 *
 * Flips completed boolean and updates timestamp
 */
export type ToggleCompleteAction = {
  type: 'TOGGLE_COMPLETE';
  payload: {
    id: string;
  };
};

/**
 * Action to delete a task
 *
 * Removes task from state.tasks array
 */
export type DeleteTaskAction = {
  type: 'DELETE_TASK';
  payload: {
    id: string;
  };
};

/**
 * Action to update filter state
 *
 * Merges payload into state.filters (partial update)
 */
export type SetFilterAction = {
  type: 'SET_FILTER';
  payload: Partial<FilterState>;
};

/**
 * Action to update sort state
 *
 * Replaces state.sort with payload (full replacement)
 */
export type SetSortAction = {
  type: 'SET_SORT';
  payload: SortState;
};

/**
 * Action to reset all filters to initial state
 *
 * No payload needed - resets to empty search, 'all' statuses
 */
export type ResetFiltersAction = {
  type: 'RESET_FILTERS';
};

/**
 * Discriminated union of all task actions
 *
 * TypeScript will narrow the payload type based on action.type
 * Exhaustive switch statements will error if any case is missing
 */
export type TaskAction =
  | AddTaskAction
  | UpdateTaskAction
  | ToggleCompleteAction
  | DeleteTaskAction
  | SetFilterAction
  | SetSortAction
  | ResetFiltersAction;

/**
 * Type guard to check if action is AddTaskAction
 */
export function isAddTaskAction(action: TaskAction): action is AddTaskAction {
  return action.type === 'ADD_TASK';
}

/**
 * Type guard to check if action is UpdateTaskAction
 */
export function isUpdateTaskAction(action: TaskAction): action is UpdateTaskAction {
  return action.type === 'UPDATE_TASK';
}

/**
 * Type guard to check if action is ToggleCompleteAction
 */
export function isToggleCompleteAction(action: TaskAction): action is ToggleCompleteAction {
  return action.type === 'TOGGLE_COMPLETE';
}

/**
 * Type guard to check if action is DeleteTaskAction
 */
export function isDeleteTaskAction(action: TaskAction): action is DeleteTaskAction {
  return action.type === 'DELETE_TASK';
}

/**
 * Type guard to check if action is SetFilterAction
 */
export function isSetFilterAction(action: TaskAction): action is SetFilterAction {
  return action.type === 'SET_FILTER';
}

/**
 * Type guard to check if action is SetSortAction
 */
export function isSetSortAction(action: TaskAction): action is SetSortAction {
  return action.type === 'SET_SORT';
}

/**
 * Type guard to check if action is ResetFiltersAction
 */
export function isResetFiltersAction(action: TaskAction): action is ResetFiltersAction {
  return action.type === 'RESET_FILTERS';
}
