"""
Backend Setup Script
Helps set up the FastAPI backend with proper configuration
"""

import secrets
import os
import sys

def generate_secret_key():
    """Generate a secure secret key"""
    return secrets.token_urlsafe(32)

def create_env_file():
    """Create .env file with user input"""
    print("\n" + "="*60)
    print("Todo App Backend Setup")
    print("="*60 + "\n")

    # Get Neon database URL
    print("1. Neon PostgreSQL Setup")
    print("-" * 60)
    print("Visit: https://console.neon.tech")
    print("Create a project and copy the connection string")
    print("\nExample format:")
    print("postgresql://user:pass@ep-xxx.region.aws.neon.tech/neondb?sslmode=require")
    print()

    database_url = input("Enter your Neon DATABASE_URL: ").strip()

    if not database_url:
        print("\n❌ DATABASE_URL is required!")
        sys.exit(1)

    if not database_url.startswith("postgresql://"):
        print("\n⚠️  Warning: DATABASE_URL should start with 'postgresql://'")

    if "sslmode=require" not in database_url:
        print("\n⚠️  Warning: Adding '?sslmode=require' to DATABASE_URL")
        database_url += "?sslmode=require" if "?" not in database_url else "&sslmode=require"

    # Generate secret key
    print("\n2. Generating SECRET_KEY...")
    secret_key = generate_secret_key()
    print(f"✅ Generated: {secret_key[:20]}...")

    # Get frontend URL
    print("\n3. Frontend Configuration")
    print("-" * 60)
    print("Enter your frontend URL (for CORS)")
    print("Local development: http://localhost:3000")
    print("Vercel: https://your-app.vercel.app")
    print()

    frontend_url = input("Enter frontend URL [http://localhost:3000]: ").strip()
    if not frontend_url:
        frontend_url = "http://localhost:3000"

    # Create .env content
    env_content = f"""# Backend Environment Variables
# Generated by setup script

# ===== Database Configuration =====
DATABASE_URL={database_url}

# ===== JWT Authentication =====
SECRET_KEY={secret_key}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30

# ===== Application Configuration =====
APP_NAME=Todo API
APP_VERSION=1.0.0

# ===== CORS Origins =====
ALLOWED_ORIGINS={frontend_url}

# ===== Logging =====
LOG_LEVEL=info
"""

    # Write .env file
    env_path = ".env"
    with open(env_path, "w") as f:
        f.write(env_content)

    print("\n" + "="*60)
    print("✅ Setup Complete!")
    print("="*60)
    print(f"\n📝 Created: {env_path}")
    print("\nNext steps:")
    print("1. Install dependencies: pip install -r requirements.txt")
    print("2. Start server: uvicorn main:app --reload --port 8000")
    print("3. Visit: http://localhost:8000/docs")
    print("\n" + "="*60 + "\n")

if __name__ == "__main__":
    try:
        create_env_file()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
